 
- id: 10.1007/s00248-019-01456-x
  image: "images/heatmap.jpg"
  tags:
    - basidiobolus
    - fungi
    - microbiome
    - slimy salamander
    
 - id: doi:10.1038/s41396-019-0416-x
   image: "images/Fig4_revised.jpg"
   tags:
    - Ophidiomyces ophidiicola
    - snake microbiome
    - microbial ecology
    - disease ecology
