- id: doi:10.1016/j.cub.2021.01.074
  date: 2021-04-26
  tags:
    - phylogeny
    - systematics
    - fungi

- id: 10.1534/g3.120.401516
  date: 2020-09-02
  tags:
    - basidiobolus
    - fungi
    - secondary metabolites
