 
- id: 10.1007/s00248-019-01456-x
  image: "images/heatmap.jpg"
  tags:
    - basidiobolus
    - fungi
    - microbiome
    - slimy salamander

- id: doi:10.1038/s41396-019-0416-x
  image: "images/Fig4_revised.jpg"
  tags:
    - Ophidiomyces ophidiicola
    - snake microbiome
    - microbial ecology
    - disease ecology
    
- id: doi:10.1016/j.cub.2021.01.074
  image: "images/phylogeny.jpg"
  tags:
    - phylogeny
    - systematics
    - fungi

- id: 10.1534/g3.120.401516
  image: "images/NRPS_phylogeny.jpg"
  tags:
    - basidiobolus
    - fungi
    - secondary metabolites
 
- id: 10.1093/femsec/fiy168
  image: "images/topdown.jpg"
  tags:
    - top down effect
    - fungi
    - terrestrial mesopredator
    - red-backed salamander
    - saprophytic fungi
 
- id: 10.1007/s10393-017-1289-y
  image: "images/ecohealth_plate.jpg"
  tags:
    - cutaneous microbiome
    - dermatophytic fungi
    - Ophidiomyces ophiodiicola
    - wildlife disease
 
- id: 10.1038/s41598-021-82607-4
  image: "olpidium.jpg"
  tags:
    - Olpidium
    - zoosporic fungi

- id: 10.3852/16-042
  image: "zoopagomycota.jpg"
  tags:
    - systematics
    - Entomophthoromycotina
    - Zoopagomycota Zoopagomycotina
    - Zygomycota
